### ISSUE TITLE
a issue about dataset

### ISSUE THREAD

**Issue by immusferr** [WenjieWWJ/Clickbait#1]
hi,wenjie 
I've been trying to run your code recently,
 but I found that the tiktok dataset byte recommendation can't be downloaded from the official website.
 So can you give me a dataset or Google drive disk access (my email address is hxl1434302006@gmail.com ）
Thank you very muchhhh.

**Comment by WenjieWWJ** [comment]
Sorry that I missed the GitHub issues. I don't save the raw dataset of Tiktok, only using a processed subset from the author of MMGCN.
