### ISSUE TITLE
About torch-sparse version problem

### ISSUE THREAD

**Issue by su-go** [WenjieWWJ/Clickbait#4]
Does torch-geometric specify a version？torch-sparse Installation failed.Ihave tried many times.

**Comment by WenjieWWJ** [comment]
I used 1.4.2 if I remember the correct conda environment. I also updated the package info in the env_file.txt for your information. Help it works. thanks.

**Comment by su-go** [comment]
> Does torch-geometric specify a version？torch-sparse Installation failed.Ihave tried many times.



> I used 1.4.2 if I remember the correct conda environment. I also updated the package info in the env_file.txt for your information. Help it works. thanks.



> I used 1.4.2 if I remember the correct conda environment. I also updated the package info in the env_file.txt for your information. Help it works. thanks.

Thank you very much! I'll try.
