### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by ning1445** [WenjieWWJ/Clickbait#6]
你好，我看到你的代码Clickbait中提供的tiktok数据集中有三个特征文件，feat_a.pt，feat_v.pt，feat_t.pt。其中feat_a.pt和feat_v.pt的维度为[34756, 128]，但是feat_t.pt的维度为[2, 261230]。这个feat_t.pt文件是否有问题呢？如果有问题的话，您能提供一下正确的feat_t.pt文件吗？非常感谢！

**Comment by WenjieWWJ** [comment]
你好，feat_t 这个文件就是这个格式，我忘记具体的含义了，261230好像是词表长度，你沿着数据处理打印一下看看，我也是用的别人的数据读入，我记得我捋过逻辑是对的，但我忘记咋回事了。

**Comment by ning1445** [comment]
我明白了，感谢您的回复
